$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $MyInvocation.MyCommand.Path

$lanIp = Get-NetIPAddress -AddressFamily IPv4 |
  Where-Object {
    $_.IPAddress -and
    $_.IPAddress -notlike '127.*' -and
    $_.IPAddress -notlike '169.254.*' -and
    $_.PrefixOrigin -ne 'WellKnown'
  } |
  Sort-Object InterfaceIndex |
  Select-Object -First 1 -ExpandProperty IPAddress

if (-not $lanIp) {
  $lanIp = '127.0.0.1'
}

$expoEnvPath = Join-Path $root 'user-app/.env.local'
$expoEnvContent = @"
# Auto-generated by start-all.ps1
# Backend URL for the current machine LAN IP.
EXPO_PUBLIC_API_BASE_URL=http://${lanIp}:5000
"@

Set-Content -Path $expoEnvPath -Value $expoEnvContent -Encoding ASCII

$services = @(
  @{
    Name = 'Backend'
    Path = Join-Path $root 'backend'
    Command = 'npm start'
  },
  @{
    Name = 'Admin Portal'
    Path = Join-Path $root 'admin-portal'
    Command = 'npm run dev'
  },
  @{
    Name = 'User App'
    Path = Join-Path $root 'user-app'
    Command = 'npm start'
  }
)

foreach ($service in $services) {
  Start-Process `
    -FilePath 'powershell.exe' `
    -WorkingDirectory $service.Path `
    -ArgumentList @('-NoLogo', '-NoExit', '-Command', $service.Command)
}

Write-Host 'Started backend, admin portal, and user app in separate PowerShell windows.'
Write-Host 'The user app runs with Expo Metro, not web, because the web bundle currently fails on react-native-maps.'
Write-Host "Expo app backend URL set to http://${lanIp}:5000"